schema: apps/api/schema.gql
documents: ''
extensions:
  codegen:
    generates:
      apps/web/src/sdk.ts:
        documents: apps/web/graphql/*.gql
        plugins:
          - typescript
          - typescript-operations
          - typescript-apollo-angular
        config:
          declarationKind: 'interface'
