schema: apps/api/schema.gql
documents: ''
extensions:
  codegen:
    generates:
      apps/web/src/sdk.ts:
        plugins:
          - fragment-matcher
          - typescript
          - typescript-apollo-angular
          - typescript-operations
        documents: apps/web/graphql/*.gql
    overwrite: true
