fragment AuthorEntry on Author {
  id
  firstName
  lastName
  gender
  createdAt
  updatedAt
}

fragment AuthorDetails on Author {
  id
  firstName
  lastName
  gender
  email
  createdAt
  updatedAt
  posts {
    id
    title
    content
    createdAt
    updatedAt
  }
}

fragment Pagination on Pagination {
  pageIndex
  pageSize
  total
}
