query AuthorSearch(
  $skip: Int = 0
  $take: Int = 10
  $where: AuthorWhereInput = {}
) {
  pagination: AuthorPagination(skip: $skip, take: $take, where: $where) {
    ...Pagination
  }
  entries: AuthorFindMany(skip: $skip, take: $take, where: $where) {
    ...AuthorEntry
  }
}

query AuthorDetails($id: String) {
  details: AuthorFindUnique(where: { id: $id }) {
    ...AuthorDetails
  }
}
