version: '3'

services:
  development:
    image: development
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ~/.ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace:cached
    environment:
      - DATABASE_URL=postgresql://user:password@database:5432/application?schema=public
    links:
      - database
      - redis
    command: sleep infinity

  database:
    image: postgres:alpine
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_DB=application
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine
    # ports:
    #   - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      # - 14250:14250
      # - 14268:14268
      - 16686:16686
      # - 5775:5775/udp
      # - 5778:5778
      # - 6831:6831/udp
      # - 6832:6832/udp
      # - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
